### PR TITLE
add link product features and wireframe

### PR DESCRIPTION
**Pull request by tmanhkha**
- Add link product features
- Add link wireframe

### CODE REVIEW

**Comment by TriDang** [comment]
There are some comments
- For the task list, please include an estimation column for the duration of these tasks. The current estimation system at Raksul is 1 for half day, so you can decide a number accordingly.
- I think there is one important task that you didn't include in this list, that is designing the database structure. In this system, we have users, roles (admin, shop manager, buyer, etc.), products, product attributes (imagine the shop manager want to add more attributes to products such as its condition (good 90%, or battery 70%, and so on), in other words, the product attributes may changes over time, do we support that feature?), do you want to store the transaction (buying and selling products)? I think at first we don't need (and we are not able) to list all the database elements, but we should design the main elements.
- The wireframe is OK. But sometimes I found there are misspell, for example "First Nam" for New admin user. The title of the "Sign up" is still "Sign in", that will make the users confused. Please check these designs again. BTW, which software or web site you use to create these wireframe?

**Comment by tmanhkha** [comment]
Thanks for your comment. I will fix it. This is the site I used to draw the wireframes [https://mockflow.com/](url)

**Comment by TriDang** [comment]
I think the wireframes you designed are well organized and easy to use. Just one suggestion: why the color of the item represents as checkbox in Add Product, but radio button in Product Details?

**Comment by TriDang** [comment]
After you fix this color issue, we will request Nhan san and Izumida san to review further.

**Comment by TriDang** [comment]
I think the sign-up page and product-detail page are not necessary at the moment. The sign-up page was replaced by the create-manager page.

**Review by TriDang — APPROVED** [review]
LGTM 👍

**Comment by TriDang** [comment]
Please review the updated changes @raksul-sian-izm

**Pull request merged**
