### PR TITLE
add authenticate user

### PR DESCRIPTION
**Pull request by tmanhkha**
### What is this change?

- Add a sign in and sign up page.

Screen Shot 2020-09-14 at 15 30 03

### CODE REVIEW

**Comment by TriDang** [comment]
Because you used a gem to provide authentication instead of implementing your own, please clarify the following issues

- The reasons behind your choice of using a gem
- What gem did you choose? Why did you choose that gem instead of others
- How you use that gem in this particular training project

Thank you!

**Comment by tmanhkha** [comment]
Thanks @TriDang 
> Because you used a gem to provide authentication instead of implementing your own, please clarify the following issues
> 
> * The reasons behind your choice of using a gem
> * What gem did you choose? Why did you choose that gem instead of others
> * How you use that gem in this particular training project
> 
> Thank you!

- I choose gems because it will help me build apps easily and faster.
-  I use devise gem because It is a popular gem in rails app for authentication (21.1k start on GitHub and updated regularly). It provided many features for authentication and easy to use.
- Steps I use the gem in training project:
 
1. Add `gem 'devise'` to Gemfile
2. Run `bundle install`
3. Run `rails g devise:install`
4. Add config to development.rb : `config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }`
5. Run generate model: `rails g devise User`
6. Run migrate: `rails db:migrate`
7. Add `before_action :authenticate_user!` to home_controller.rb
8. Generate views: `rails generate devise:views`

**Review by TriDang — COMMENTED** [review]
Did the registration form generated have the same UI as the wireframe you designed previously? If not, please make appropriate changes.

**Comment by tmanhkha** [comment]
> �Did the registration form generated have the same UI as the wireframe you designed previously? If not, please make appropriate changes.

I have updated my pull request and add screenshot. Can you review it? @TriDang.
Thank you.

**Comment by TriDang** [comment]
Please check if the "Creating a new manager" interface can be implemented quickly. If not, you can proceed for the next step of "Adding a new product from a manager".

**Pull request closed without merging**
