### PR TITLE
add database design

### PR DESCRIPTION
**Pull request by tmanhkha**
- Add database design

### CODE REVIEW

**Comment by TriDang** [comment]
Some comments
- Why there is an `id` field for `users` and `roles` tables, but not for `products` table?
- Why do you need to store `password_confirmation` of a user?
- Have you considered storing products with the same manufacturer semantically?
- I didn't see the `quantity` field of product. But I remember there is `quantity` in Add New Product UI?

**Comment by tmanhkha** [comment]
@TriDang Thanks for your comment. 
Can I create a new table called manufacturer? It will store the manufacturer name.

**Review by TriDang — CHANGES_REQUESTED** [review]
Please think about below issues

- A model is from a particular manufacturer, so is it necessary to add both model_id and manufacturer_id into product?
- In case you want to store many information about memory, such as capacity, hardware type, memory manufacturer, etc. then I think just storing a number is enough.
- Still I do not see the `quantity` for product. So, how do we know if a product is still available to sell to customers?

**Comment by tmanhkha** [comment]
@TriDang 
1. I think it is necessary. Because it will help users to use and manage more easily. For example, they would use a select box instead of a text box. And will also avoid confusion from users.
2.  I will fix it
3. After Shian review pull request for me on the product-features-and-wireframe branch.
We will have four properties of the product.
- Manufacturer
- Model
- Data memory
- Price

**Comment by TriDang** [comment]
I have only one suggestion to add:
Currently, you use 2 foreign keys `model_id` and `data_memory_id` to denote the model and the memory version of a product. However, because you already defined `data_memory_models` table, the 2 foreign keys above can be replaced by just one key `data_memory_model_id`.

**Review by TriDang — APPROVED** [review]

**Comment by TriDang** [comment]
Please review the database design @NhanHo

**Comment by NhanHo** [comment]
OK, please move on to the next step @tmanhkha

**Review by NhanHo — APPROVED** [review]

**Pull request merged**
